# Generated by Django 2.1.7 on 2019-05-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
