# Generated by Django 2.1.7 on 2019-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190320_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Images',
            new_name='Image',
        ),
    ]
